/*
 Navicat Premium Data Transfer

 Source Server         : 长城网数据库
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : 192.168.251.17:1521
 Source Schema         : BJCCSY

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 27/09/2022 10:53:53
*/


-- ----------------------------
-- Table structure for DETOX_CAPTURE_TAKE_DRUGS
-- ----------------------------
DROP TABLE "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS";
CREATE TABLE "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS" (
  "CASE_ID" VARCHAR2(32 BYTE) NOT NULL,
  "CASE_NAME" VARCHAR2(255 BYTE) NOT NULL,
  "PERSON" VARCHAR2(32 BYTE) NOT NULL,
  "SEX" CHAR(1 BYTE) NOT NULL,
  "BIRTH_TIME" DATE NOT NULL,
  "ID_CARD" VARCHAR2(32 BYTE) NOT NULL,
  "RESOLVE_RESULT" CHAR(1 BYTE) NOT NULL,
  "RESOLVE_TIME" DATE NOT NULL,
  "SPONSOR_MAIN" VARCHAR2(32 BYTE) NOT NULL,
  "FORCED_QUARANTINE" CHAR(1 BYTE) NOT NULL,
  "DATA_ID" VARCHAR2(32 BYTE) NOT NULL,
  "CREATED_TIME" DATE NOT NULL
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS"."CASE_ID" IS '案件id';
COMMENT ON COLUMN "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS"."CASE_NAME" IS '案件名称';
COMMENT ON COLUMN "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS"."PERSON" IS '姓名';
COMMENT ON COLUMN "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS"."SEX" IS '性别 0男/1女';
COMMENT ON COLUMN "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS"."BIRTH_TIME" IS '出生日期';
COMMENT ON COLUMN "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS"."ID_CARD" IS '身份证号';
COMMENT ON COLUMN "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS"."RESOLVE_RESULT" IS '决定结果 0行政拘留  1行政拘留（不予执行）/2罚款';
COMMENT ON COLUMN "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS"."RESOLVE_TIME" IS '决定时间';
COMMENT ON COLUMN "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS"."SPONSOR_MAIN" IS '主办单位';
COMMENT ON COLUMN "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS"."FORCED_QUARANTINE" IS '是否强制隔离 0是/1否';
COMMENT ON COLUMN "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS"."DATA_ID" IS '数据id';
COMMENT ON COLUMN "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS"."CREATED_TIME" IS '创建时间';
COMMENT ON TABLE "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS" IS '吸毒人员案件表';

-- ----------------------------
-- Records of DETOX_CAPTURE_TAKE_DRUGS
-- ----------------------------
INSERT INTO "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS" VALUES ('1', '吸毒', '张三', '1', TO_DATE('2000-02-02 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '411528200002055418', '0', TO_DATE('2022-09-26 21:28:51', 'SYYYY-MM-DD HH24:MI:SS'), '北京市公安局', '0', '2', TO_DATE('2022-09-26 21:29:13', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Primary Key structure for table DETOX_CAPTURE_TAKE_DRUGS
-- ----------------------------
ALTER TABLE "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS" ADD CONSTRAINT "SYS_C0012770" PRIMARY KEY ("CASE_ID");

-- ----------------------------
-- Checks structure for table DETOX_CAPTURE_TAKE_DRUGS
-- ----------------------------
ALTER TABLE "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS" ADD CONSTRAINT "SYS_C0012761" CHECK ("CASE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS" ADD CONSTRAINT "SYS_C0012762" CHECK ("CASE_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS" ADD CONSTRAINT "SYS_C0012763" CHECK ("PERSON" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS" ADD CONSTRAINT "SYS_C0012764" CHECK ("SEX" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS" ADD CONSTRAINT "SYS_C0012765" CHECK ("BIRTH_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS" ADD CONSTRAINT "SYS_C0012766" CHECK ("ID_CARD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS" ADD CONSTRAINT "SYS_C0012767" CHECK ("RESOLVE_RESULT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS" ADD CONSTRAINT "SYS_C0012768" CHECK ("RESOLVE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS" ADD CONSTRAINT "SYS_C0012769" CHECK ("SPONSOR_MAIN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS" ADD CONSTRAINT "SYS_C0012771" CHECK ("FORCED_QUARANTINE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS" ADD CONSTRAINT "SYS_C0012787" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS" ADD CONSTRAINT "SYS_C0012822" CHECK ("CREATED_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS" ADD CONSTRAINT "SYS_C0044122" CHECK ("CASE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS" ADD CONSTRAINT "SYS_C0044123" CHECK ("CASE_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS" ADD CONSTRAINT "SYS_C0044124" CHECK ("PERSON" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS" ADD CONSTRAINT "SYS_C0044125" CHECK ("SEX" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS" ADD CONSTRAINT "SYS_C0044126" CHECK ("BIRTH_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS" ADD CONSTRAINT "SYS_C0044127" CHECK ("ID_CARD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS" ADD CONSTRAINT "SYS_C0044128" CHECK ("RESOLVE_RESULT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS" ADD CONSTRAINT "SYS_C0044129" CHECK ("RESOLVE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS" ADD CONSTRAINT "SYS_C0044130" CHECK ("SPONSOR_MAIN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS" ADD CONSTRAINT "SYS_C0044131" CHECK ("FORCED_QUARANTINE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS" ADD CONSTRAINT "SYS_C0044132" CHECK ("DATA_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "BJCCSY"."DETOX_CAPTURE_TAKE_DRUGS" ADD CONSTRAINT "SYS_C0044133" CHECK ("CREATED_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
